import type { Metadata } from 'next';
import Link from 'next/link';
import Box from '@mui/material/Box';
import { LegalLayout } from '@/components/layout/LegalLayout';

export const metadata: Metadata = {
  title: 'AI Disclosure',
  description:
    'How Periplo uses generative AI, what data is sent to AI providers, and the limitations of AI-generated travel recommendations.',
  alternates: { canonical: '/legal/ai-disclosure' },
};

export default function AiDisclosurePage() {
  return (
    <LegalLayout title="AI Disclosure" lastUpdated="April 19, 2026">
      <p>
        Periplo uses generative AI to plan trips, suggest activities, and power
        its in-app chat. This page explains what that means for you and what the
        limitations are. It is provided in line with applicable transparency
        obligations, including the EU AI Act (Art. 50).
      </p>

      <h2>1. You are interacting with AI</h2>
      <p>
        When you generate a trip, ask the in-app chat a question, or use the
        &quot;Discover&quot; feature, your request is processed by large
        language models provided by third parties. Responses are synthetic
        &mdash; they are generated by an AI system, not written by a human.
      </p>
      <p>The app clearly labels AI-generated content within the user interface.</p>

      <h2>2. AI providers we use</h2>
      <ul>
        <li>
          <strong>Google Gemini</strong> &mdash; trip routing, itinerary
          planning, destination information
        </li>
        <li>
          <strong>OpenAI</strong> &mdash; specialized activity recommendations,
          chat, and web-grounded search
        </li>
      </ul>
      <p>
        Both providers process data under their own privacy policies and
        data-processing agreements with us. Neither is authorized to use your
        data to train their foundation models.
      </p>

      <h2>3. What data is sent to AI providers</h2>
      <ul>
        <li>Your trip inputs (destinations, dates, interests, preferences)</li>
        <li>
          Approximate location when relevant to the query (city-level, not
          precise GPS)
        </li>
        <li>
          Relevant prior context from your current session (e.g., the itinerary
          being modified)
        </li>
      </ul>
      <p>
        We do <strong>not</strong> send your name, email address, authentication
        credentials, payment information, or device identifiers to AI providers.
      </p>

      <h2>4. Limitations of AI-generated recommendations</h2>
      <p>
        AI output may be inaccurate, incomplete, or out of date. We strongly
        recommend verifying the following independently before acting on any AI
        suggestion:
      </p>
      <ul>
        <li>Opening hours, ticket prices, and availability of venues</li>
        <li>Visa, entry, and safety requirements</li>
        <li>Weather and seasonal conditions</li>
        <li>Travel times, routes, and transport options</li>
        <li>Reservation or booking requirements</li>
      </ul>

      <Box
        sx={{
          bgcolor: 'rgba(196, 96, 58, 0.08)',
          borderLeft: '3px solid',
          borderColor: 'primary.main',
          borderRadius: '0 12px 12px 0',
          p: '16px 20px',
          my: 2,
          '& p:last-child': { mb: 0 },
        }}
      >
        <p>
          <strong>
            Periplo is a planning assistant, not a substitute for official
            travel, safety, legal, medical, or financial advice.
          </strong>{' '}
          Always consult authoritative sources (official tourism boards,
          embassies, airlines, venues) before you travel.
        </p>
      </Box>

      <h2>5. No automated decisions affecting legal rights</h2>
      <p>
        Periplo does not use AI to make decisions that produce legal effects or
        significantly affect you (for example, eligibility, pricing
        individualization, or automated refusals of service). All content
        generated by the AI is informational only; you remain in full control of
        whether to follow any suggestion.
      </p>

      <h2>6. Human oversight</h2>
      <p>
        You can modify any AI-generated itinerary directly in the app &mdash;
        add, remove, or rearrange activities; override recommendations; or
        disregard the output entirely. If you feel an output is inaccurate,
        harmful, or misleading, please report it using the feedback option in
        the app or email us (see below).
      </p>

      <h2>7. Reporting issues with AI output</h2>
      <p>
        To report an AI-generated response that is factually wrong, harmful,
        offensive, or otherwise problematic, contact us at{' '}
        <a href="mailto:support@periploapp.com">support@periploapp.com</a> with
        a description of the issue and, if possible, a screenshot. We review all
        reports and use them to improve the service.
      </p>

      <h2>8. Related policies</h2>
      <p>
        See also: <Link href="/legal/privacy">Privacy Policy</Link> (how data is
        processed) and <Link href="/legal/terms">Terms of Service</Link> &sect;
        5 (liability and disclaimers for AI-generated content).
      </p>

      <h2>9. Contact</h2>
      <Box
        sx={{
          bgcolor: 'action.hover',
          borderRadius: 1.5,
          p: 2.5,
          mt: 3,
          '& p': { mb: 1, '&:last-child': { mb: 0 } },
        }}
      >
        <p>Questions about how Periplo uses AI?</p>
        <p>
          <a href="mailto:support@periploapp.com">support@periploapp.com</a>
        </p>
      </Box>
    </LegalLayout>
  );
}
