import type { MetadataRoute } from 'next';
import fs from 'node:fs';
import path from 'node:path';
import { destinations } from '@/data/destinations';
import { blogPosts } from '@/data/blogPosts';

type SeoManifest = {
  generated_at: string;
  destinations: string[];
  itineraries: string[];
};

// Slugs emitted by tripgen_backend/scripts/generate_seo_pages.py into
// public/seo-manifest.json. Fail-soft: if the file is missing or
// malformed (e.g. the generator hasn't run in this checkout), return an
// empty manifest so the sitemap still builds.
function readSeoManifest(): SeoManifest {
  try {
    const raw = fs.readFileSync(
      path.join(process.cwd(), 'public/seo-manifest.json'),
      'utf-8',
    );
    const parsed = JSON.parse(raw) as SeoManifest;
    return {
      generated_at: parsed.generated_at ?? '',
      destinations: Array.isArray(parsed.destinations) ? parsed.destinations : [],
      itineraries: Array.isArray(parsed.itineraries) ? parsed.itineraries : [],
    };
  } catch {
    return { generated_at: '', destinations: [], itineraries: [] };
  }
}

const BASE_URL = 'https://periploapp.com';

// /mcp-upgrade is intentionally excluded — it's noindex.
const LEGAL_SLUGS = [
  'privacy',
  'terms',
  'help',
  'delete-account',
  'dsa',
  'affiliate-disclosure',
  'ai-disclosure',
  'mcp',
] as const;

// Captured once per build — used as the lastModified for surfaces whose
// content is generated rather than edited in a single source file.
const BUILD_TIME = new Date();

function fileModified(relPath: string): Date {
  try {
    return fs.statSync(path.join(process.cwd(), relPath)).mtime;
  } catch {
    return BUILD_TIME;
  }
}

// Parses blog post.date strings like "March 15, 2026" into a Date. Falls
// back to BUILD_TIME if the date is unparseable so we never emit invalid
// <lastmod> entries.
function parseBlogDate(dateStr: string): Date {
  const d = new Date(dateStr);
  return Number.isNaN(d.getTime()) ? BUILD_TIME : d;
}

export default function sitemap(): MetadataRoute.Sitemap {
  const destinationsModified = fileModified('src/data/destinations.ts');

  const home: MetadataRoute.Sitemap = [
    {
      url: `${BASE_URL}/`,
      lastModified: BUILD_TIME,
      changeFrequency: 'weekly',
      priority: 1.0,
    },
  ];

  const topMarketing: MetadataRoute.Sitemap = (
    [
      { path: '/pricing', src: 'src/app/(marketing)/pricing/page.tsx' },
      { path: '/faq', src: 'src/app/(marketing)/faq/page.tsx' },
      { path: '/blog', src: 'src/app/(marketing)/blog/page.tsx' },
      { path: '/community', src: 'src/app/(marketing)/community/page.tsx' },
      { path: '/explore', src: 'src/app/(app)/explore/page.tsx' },
    ] as const
  ).map(({ path: p, src }) => ({
    url: `${BASE_URL}${p}`,
    lastModified: fileModified(src),
    changeFrequency: 'weekly' as const,
    priority: 0.9,
  }));

  const blogPages: MetadataRoute.Sitemap = blogPosts.map((p) => ({
    url: `${BASE_URL}/blog/${p.slug}`,
    lastModified: parseBlogDate(p.date),
    changeFrequency: 'monthly',
    priority: 0.7,
  }));

  // Each destination renders at two indexable surfaces:
  //   /explore/[slug]                — canonical (live picks)
  //   /community/guides/[slug]       — static guide, canonicalizes to /explore
  // /community/[slug] is intentionally excluded: that route serves
  // user-published trip templates with their own slug namespace, not
  // destination slugs.
  const destinationPages: MetadataRoute.Sitemap = destinations.flatMap((d) => [
    {
      url: `${BASE_URL}/explore/${d.slug}`,
      lastModified: destinationsModified,
      changeFrequency: 'weekly',
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/community/guides/${d.slug}`,
      lastModified: destinationsModified,
      changeFrequency: 'monthly',
      priority: 0.6,
    },
  ]);

  const legalPages: MetadataRoute.Sitemap = LEGAL_SLUGS.map((slug) => ({
    url: `${BASE_URL}/legal/${slug}`,
    lastModified: fileModified(`src/app/legal/${slug}/page.tsx`),
    changeFrequency: 'yearly',
    priority: 0.3,
  }));

  // SEO landing pages generated by the Python script into
  // public/destinations/* and public/itineraries/*. lastModified tracks
  // the manifest's mtime so a regeneration bumps every URL together.
  const manifest = readSeoManifest();
  const manifestModified = fileModified('public/seo-manifest.json');
  const seoDestinations: MetadataRoute.Sitemap = manifest.destinations.map((slug) => ({
    url: `${BASE_URL}/destinations/${slug}/`,
    lastModified: manifestModified,
    changeFrequency: 'weekly',
    priority: 0.7,
  }));
  const seoItineraries: MetadataRoute.Sitemap = manifest.itineraries.map((slug) => ({
    url: `${BASE_URL}/itineraries/${slug}/`,
    lastModified: manifestModified,
    changeFrequency: 'weekly',
    priority: 0.7,
  }));

  return [
    ...home,
    ...topMarketing,
    ...blogPages,
    ...destinationPages,
    ...legalPages,
    ...seoDestinations,
    ...seoItineraries,
  ];
}
